/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vitalityvault;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 *
 * @author deand
 */
public class VVCalTrackerGUI extends javax.swing.JFrame {

    private int totCalCount = 0;
    Connection myConn;//declare instance of Connection class

    /**
     * Creates new form VitalityVaultCalTrackerGUI
     */
    public VVCalTrackerGUI() {
        initComponents();
        getConnection();
    }

    private void getConnection() {
        try {
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/VV", "dean_dolan", "temppassword");
        } catch (SQLException e) {
            System.out.println("Error connecting" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        calIntakeBtn = new javax.swing.JButton();
        foodCalCheckerBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        titleLbl.setFont(new java.awt.Font("Verdana Pro Cond", 1, 36)); // NOI18N
        titleLbl.setText(" Vitality Vault");

        calIntakeBtn.setText("Calorie Intake");
        calIntakeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calIntakeBtnActionPerformed(evt);
            }
        });

        foodCalCheckerBtn.setText("Food Calorie Checker");
        foodCalCheckerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodCalCheckerBtnActionPerformed(evt);
            }
        });

        jButton1.setText("<- Prev");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calIntakeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodCalCheckerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calIntakeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodCalCheckerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VVCalTrackerGUI closeGUI = new VVCalTrackerGUI();
        closeGUI.setVisible(false);
        vvworkout myGUI = new vvworkout();
        myGUI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void foodCalCheckerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodCalCheckerBtnActionPerformed
        // TODO add your handling code here:
        try {
            Statement myStatement = myConn.createStatement();
            ResultSet myRs = myStatement.executeQuery("SELECT * FROM foods.foods");

            while (myRs.next()) {
                JOptionPane.showMessageDialog(null, "Calories: " + myRs.getString("Calories"));
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_foodCalCheckerBtnActionPerformed

    private void calIntakeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calIntakeBtnActionPerformed
        // Prompt the user for the month
        String selectedMonth = (String) JOptionPane.showInputDialog(
                null,
                "Select the month:",
                "Month Selection",
                JOptionPane.PLAIN_MESSAGE,
                null,
                new String[]{"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"},
                "January");

        if (selectedMonth != null) { // User clicked OK
            // Prompt the user for the day
            String dayStr = JOptionPane.showInputDialog(null, "Enter the day (1-31):");
            if (dayStr != null) { // User clicked OK
                try {
                    int day = Integer.parseInt(dayStr);
                    int maxDay = getMaxDay(selectedMonth);

                    if (day < 1 || day > maxDay) {
                        JOptionPane.showMessageDialog(null, "Invalid day for " + selectedMonth + ". Please enter a number between 1 and " + maxDay + ".");
                        return;
                    }

                    // Prompt the user for the calorie intake
                    String calIntakeStr = JOptionPane.showInputDialog(null, "Enter calorie intake:");
                    if (calIntakeStr != null) { // User clicked OK
                        try {
                            int calIntake = Integer.parseInt(calIntakeStr);

                            // Insert the calorie intake into the database table
                            // Here you should write your code to insert the calorie intake into the database
                            // You will need to use the selectedMonth, day, and calIntake variables to determine
                            // the corresponding spot in the table and insert the value
                            // For demonstration purposes, let's just print the values
                            System.out.println("Month: " + selectedMonth + ", Day: " + day + ", Calorie Intake: " + calIntake);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "Invalid calorie intake. Please enter a valid integer.");
                        }
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Invalid day. Please enter a valid integer.");
                }
            }
        }
    }

// Method to get the maximum day for a given month
    private int getMaxDay(String month) {
        switch (month) {
            case "February":
                return 28; // Assuming not a leap year
            case "April":
            case "June":
            case "September":
            case "November":
                return 30;
            default:
                return 31;
        }
    }//GEN-LAST:event_calIntakeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVCalTrackerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calIntakeBtn;
    private javax.swing.JButton foodCalCheckerBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

}
