/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vitalityvault;

import java.util.ArrayList;

/**
 *
 * @author deand
 */
public class VVSignUpGUI extends javax.swing.JFrame {
    private ArrayList<VVSignUp> details = new ArrayList<>();
    
    /**
     * Creates new form VitalityVaultHomeGUI
     */
    public VVSignUpGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPan = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        bodyPan = new javax.swing.JPanel();
        signInPan = new javax.swing.JPanel();
        signInLbl = new javax.swing.JLabel();
        usernameBtn = new javax.swing.JButton();
        passwordBtn = new javax.swing.JButton();
        signUpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        navPan.setBackground(new java.awt.Color(0, 204, 204));

        titleLbl.setFont(new java.awt.Font("Verdana Pro Cond", 1, 36)); // NOI18N
        titleLbl.setText(" Vitality Vault");

        javax.swing.GroupLayout navPanLayout = new javax.swing.GroupLayout(navPan);
        navPan.setLayout(navPanLayout);
        navPanLayout.setHorizontalGroup(
            navPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navPanLayout.setVerticalGroup(
            navPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navPanLayout.createSequentialGroup()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bodyPan.setBackground(new java.awt.Color(0, 204, 204));

        signInLbl.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        signInLbl.setText("Sign Up:");

        usernameBtn.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        usernameBtn.setText("Username");
        usernameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameBtnActionPerformed(evt);
            }
        });

        passwordBtn.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        passwordBtn.setText("Password");
        passwordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBtnActionPerformed(evt);
            }
        });

        signUpBtn.setFont(new java.awt.Font("Verdana Pro", 1, 14)); // NOI18N
        signUpBtn.setText("Sign Up");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signInPanLayout = new javax.swing.GroupLayout(signInPan);
        signInPan.setLayout(signInPanLayout);
        signInPanLayout.setHorizontalGroup(
            signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanLayout.createSequentialGroup()
                .addGroup(signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signInPanLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(signInLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signInPanLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameBtn)))
                    .addGroup(signInPanLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(signUpBtn)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        signInPanLayout.setVerticalGroup(
            signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(signInLbl)
                .addGap(18, 18, 18)
                .addComponent(usernameBtn)
                .addGap(18, 18, 18)
                .addComponent(passwordBtn)
                .addGap(18, 18, 18)
                .addComponent(signUpBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyPanLayout = new javax.swing.GroupLayout(bodyPan);
        bodyPan.setLayout(bodyPanLayout);
        bodyPanLayout.setHorizontalGroup(
            bodyPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(signInPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        bodyPanLayout.setVerticalGroup(
            bodyPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signInPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameBtnActionPerformed

    private void passwordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordBtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVSignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVSignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVSignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVSignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVSignUpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPan;
    private javax.swing.JPanel navPan;
    private javax.swing.JButton passwordBtn;
    private javax.swing.JLabel signInLbl;
    private javax.swing.JPanel signInPan;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton usernameBtn;
    // End of variables declaration//GEN-END:variables
}
